---
apiVersion: v1
kind: Service
metadata:
  name:  apigw-microapigw
  namespace: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: generator-api
