---
apiVersion: v1
kind: Service
metadata:
  name: apigw-microapigw
  namespace: apigw
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nginx-plus-apigw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-plus-apigw
  name: nginx-plus-apigw
  namespace: apigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-plus-apigw
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-plus-apigw
    spec:
      containers:
      - image: private-registry.nginx.com/nginx-plus/base:r32-ubi-9
        name: base
        volumeMounts:
        - mountPath: /etc/nginx/
          name: nginx-conf
          readOnly: false
        ports:
        - name: http 
          containerPort: 8080
      imagePullSecrets:
      - name: token-f5-trial
      volumes:
      - name: nginx-conf
        persistentVolumeClaim:
          claimName: azure-managed-disk

