apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: azure-managed-disk
    namespace: apigw
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi
